-- ELENOR WAR TRACKER V3
-- Executar uma vez no Supabase SQL Editor.

create table if not exists public.tracker_groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  kind text not null default 'guild' check (kind in ('guild','randoms')),
  wot_guild_id integer,
  guild_url text,
  active boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now()
);

alter table public.players add column if not exists group_id uuid references public.tracker_groups(id) on delete set null;
alter table public.players add column if not exists source text default 'wotserver';
alter table public.players add column if not exists source_url text;
alter table public.players add column if not exists last_error text;
alter table public.players add column if not exists xp bigint;
alter table public.players add column if not exists xp_per_hour numeric;
alter table public.players add column if not exists xp_updated_at timestamptz;
alter table public.players add column if not exists last_xp_gain_at timestamptz;
alter table public.players add column if not exists xp_checked_at timestamptz;

insert into public.tracker_groups(name,slug,kind,wot_guild_id,guild_url,active,sort_order)
values ('Soul Tatics','soul-tatics','guild',166,'https://www.wotserver.com/?view=guilds&action=show&guild=166',true,10)
on conflict (slug) do update set
  name=excluded.name,
  kind=excluded.kind,
  wot_guild_id=excluded.wot_guild_id,
  guild_url=excluded.guild_url,
  active=true;

insert into public.tracker_groups(name,slug,kind,active,sort_order)
values ('RANDOMS','randoms','randoms',true,999)
on conflict (slug) do update set name='RANDOMS',kind='randoms',active=true;

update public.players p
set group_id=g.id
from public.tracker_groups g
where p.group='soul' and g.slug='soul-tatics' and p.group_id is null;

-- Histórico de XP
create table if not exists public.player_xp_history (
  id bigint generated by default as identity primary key,
  player_id uuid references public.players(id) on delete cascade,
  player_name text not null,
  xp bigint not null,
  level integer,
  recorded_at timestamptz not null default now()
);
create index if not exists idx_player_xp_history_player_time on public.player_xp_history(player_id,recorded_at desc);

-- Lock do coletor
create table if not exists public.elenor_collector_lock (
  id integer primary key,
  locked_until timestamptz not null default now()
);
insert into public.elenor_collector_lock(id,locked_until) values(1,now()) on conflict(id) do nothing;

create or replace function public.try_elenor_collector_lock(p_seconds integer default 30)
returns boolean language plpgsql security definer set search_path=public as $$
declare ok boolean;
begin
  update public.elenor_collector_lock
     set locked_until=now()+make_interval(secs=>p_seconds)
   where id=1 and locked_until<=now();
  GET DIAGNOSTICS ok = ROW_COUNT;
  ok := (ok::integer > 0);
  return ok;
end; $$;

create or replace function public.finish_elenor_collector_lock()
returns boolean language plpgsql security definer set search_path=public as $$
begin
  update public.elenor_collector_lock set locked_until=now() where id=1;
  return true;
end; $$;

grant execute on function public.try_elenor_collector_lock(integer) to anon,authenticated,service_role;
grant execute on function public.finish_elenor_collector_lock() to anon,authenticated,service_role;
grant select on public.tracker_groups,public.players to anon,authenticated;
grant insert,update,delete on public.tracker_groups,public.players to authenticated;
grant select,insert,update,delete on public.player_xp_history,public.elenor_collector_lock to service_role;

alter table public.tracker_groups enable row level security;
alter table public.players enable row level security;

-- Leitura pública: o viewer pode mostrar também OFFLINE.
drop policy if exists tracker_groups_public_read on public.tracker_groups;
create policy tracker_groups_public_read on public.tracker_groups for select using (active=true);

drop policy if exists players_public_read on public.players;
create policy players_public_read on public.players for select using (true);

-- Somente usuários cadastrados em admins podem alterar configurações/jogadores.
drop policy if exists tracker_groups_admin_write on public.tracker_groups;
create policy tracker_groups_admin_write on public.tracker_groups for all to authenticated using (exists(select 1 from public.admins a where a.user_id=auth.uid())) with check (exists(select 1 from public.admins a where a.user_id=auth.uid()));

drop policy if exists players_admin_write on public.players;
create policy players_admin_write on public.players for all to authenticated using (exists(select 1 from public.admins a where a.user_id=auth.uid())) with check (exists(select 1 from public.admins a where a.user_id=auth.uid()));
