-- Migração complementar para o coletor sync-wotserver
alter table public.players add column if not exists xp bigint;
alter table public.players add column if not exists xp_per_hour numeric;
alter table public.players add column if not exists xp_updated_at timestamptz;
alter table public.players add column if not exists last_xp_gain_at timestamptz;
alter table public.players add column if not exists xp_checked_at timestamptz;
alter table public.players add column if not exists source text default 'wotserver';
alter table public.players add column if not exists source_url text;
alter table public.players add column if not exists last_error text;

create table if not exists public.player_xp_history (
  id bigint generated by default as identity primary key,
  player_id uuid references public.players(id) on delete cascade,
  player_name text not null,
  xp bigint not null,
  level integer,
  recorded_at timestamptz not null default now()
);
alter table public.player_xp_history add column if not exists level integer;
alter table public.player_xp_history add column if not exists recorded_at timestamptz not null default now();
create index if not exists idx_player_xp_history_player_time on public.player_xp_history(player_id, recorded_at desc);
grant select, insert, update, delete on public.players to service_role;
grant select, insert, update, delete on public.player_xp_history to service_role;

create table if not exists public.elenor_collector_lock (
  id integer primary key,
  locked_until timestamptz not null default now()
);
insert into public.elenor_collector_lock(id,locked_until) values(1,now()) on conflict(id) do nothing;

create or replace function public.try_elenor_collector_lock(p_seconds integer default 20)
returns boolean language plpgsql security definer set search_path=public as $$
declare ok boolean;
begin
  update public.elenor_collector_lock
     set locked_until=now() + make_interval(secs => p_seconds)
   where id=1 and locked_until <= now();
  get diagnostics ok = row_count > 0;
  return ok;
end; $$;

create or replace function public.finish_elenor_collector_lock()
returns boolean language plpgsql security definer set search_path=public as $$
begin
  update public.elenor_collector_lock set locked_until=now() where id=1;
  return true;
end; $$;

grant execute on function public.try_elenor_collector_lock(integer) to anon, authenticated, service_role;
grant execute on function public.finish_elenor_collector_lock() to anon, authenticated, service_role;
