const sb=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_KEY);const rows=document.querySelector('#rows');
const fmt=n=>n==null?'—':Number(n).toLocaleString('pt-BR');
const rate=n=>n==null?'—':(Number(n)>=1e9?(Number(n)/1e9).toFixed(2)+'B/h':Number(n)>=1e6?(Number(n)/1e6).toFixed(2)+'M/h':Number(n).toLocaleString('pt-BR')+'/h');
function ago(iso){if(!iso)return '—';const s=Math.max(0,Math.floor((Date.now()-Date.parse(iso))/1000));if(s<60)return s+'s';const m=Math.floor(s/60);if(m<60)return m+'m '+s%60+'s';return Math.floor(m/60)+'h '+m%60+'m';}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function render(list){let up=0,stop=0,off=0;const sorted=[...list].sort((a,b)=>{const sa=a.status==='offline'?2:a.status==='online'?0:1;const sb=b.status==='offline'?2:b.status==='online'?0:1;return sa-sb||(b.level||0)-(a.level||0);});rows.innerHTML=sorted.map(p=>{const stale=!p.last_xp_gain_at||Date.now()-Date.parse(p.last_xp_gain_at)>=180000;const status=p.status==='offline'?'offline':stale?'pz':'online';if(status==='online')up++;else if(status==='pz')stop++;else off++;const label=status==='online'?'🟢 UPANDO':status==='pz'?'🟡 ONLINE / PARADO':'⚫ OFFLINE';const hot=status==='online'&&p.last_xp_gain_at&&Date.now()-Date.parse(p.last_xp_gain_at)<30000?' hot':'';return `<tr class="${status}${hot}"><td><b>${escapeHtml(p.name)}</b></td><td>${fmt(p.level)}</td><td>${label}</td><td>${fmt(p.xp)}</td><td>${status==='online'?rate(p.xp_per_hour):'—'}</td><td>${p.last_xp_gain_at?ago(p.last_xp_gain_at):'—'}</td></tr>`;}).join('')||'<tr><td colspan="6">Nenhum personagem encontrado.</td></tr>';document.querySelector('#up').textContent=up;document.querySelector('#stop').textContent=stop;document.querySelector('#off').textContent=off;document.querySelector('#updated').textContent=new Date().toLocaleTimeString('pt-BR');}
async function collect(){const el=document.querySelector('#sync');try{el.textContent='Coletando...';const r=await fetch(window.SUPABASE_URL+'/functions/v1/sync-wotserver',{method:'POST',headers:{apikey:window.SUPABASE_KEY,'Content-Type':'application/json'},body:'{}',cache:'no-store'});const j=await r.json();el.textContent=j.skipped?'Outra aba está sincronizando':'Sincronizado '+new Date().toLocaleTimeString('pt-BR');}catch(e){el.textContent='Erro na sincronização';console.warn(e);}}
async function load(){const {data,error}=await sb.from('players').select('name,level,status,xp,xp_per_hour,last_xp_gain_at').eq('group','soul').order('name');if(error){rows.innerHTML=`<tr><td colspan="6">Erro: ${escapeHtml(error.message)}</td></tr>`;return;}render(data||[]);}
function clock(){document.querySelector('#clock').textContent=new Date().toLocaleTimeString('pt-BR');}
async function cycle(){await collect();await load();}
cycle();setInterval(cycle,10000);setInterval(load,2000);setInterval(clock,1000);clock();