const db=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_KEY);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=n=>n==null?'—':Number(n).toLocaleString('pt-BR');
const rate=n=>n==null?'—':Number(n)>=1e9?(Number(n)/1e9).toFixed(2)+'B/h':Number(n)>=1e6?(Number(n)/1e6).toFixed(2)+'M/h':Number(n).toLocaleString('pt-BR')+'/h';
function ago(iso){if(!iso)return '—';const s=Math.max(0,Math.floor((Date.now()-Date.parse(iso))/1000));if(s<60)return s+'s';const m=Math.floor(s/60);if(m<60)return m+'m '+s%60+'s';return Math.floor(m/60)+'h '+m%60+'m'}
function statusOf(p){if(p.status==='offline')return'offline';return p.last_xp_gain_at&&Date.now()-Date.parse(p.last_xp_gain_at)<180000?'online':'pz'}
function exiva(name){const cmd=`exiva \"${name}\"`;navigator.clipboard?.writeText(cmd).catch(()=>{})}
let state={groups:[],players:[],deaths:[],daily:{},search:'',filter:'all'};
function render(){const {groups,players,deaths,daily}=state;let up=0,stop=0,off=0;const q=state.search.trim().toLowerCase();
const html=groups.filter(g=>g.active).map(g=>{let list=players.filter(p=>(p.group_id===g.id||(!p.group_id&&p.group===g.slug))&&(!q||p.name.toLowerCase().includes(q))&&(state.filter==='all'||statusOf(p)===state.filter)).sort((a,b)=>{const sa=statusOf(a),sb=statusOf(b),rank={online:0,pz:1,offline:2};return rank[sa]-rank[sb]||(daily[b.id]||0)-(daily[a.id]||0)||(b.xp_per_hour||0)-(a.xp_per_hour||0)||a.name.localeCompare(b.name)});if(!list.length)return'';let body=list.map(p=>{const s=statusOf(p);if(s==='online')up++;else if(s==='pz')stop++;else off++;const cls=s==='online'?'s-up':s==='pz'?'s-pz':'s-off',label=s==='online'?'UPANDO':s==='pz'?'ONLINE / PARADO':'OFFLINE';return `<tr><td><div class="player"><b>${esc(p.name)}</b><button class="copy-exiva" title="Copiar exiva" onclick='exiva(${JSON.stringify(p.name)})'>⧉ exiva</button></div></td><td>${fmt(p.level)}</td><td><span class="status ${cls}"><i class="dot"></i>${label}</span></td><td>${s==='online'?rate(p.xp_per_hour):'—'}</td><td>${p.last_xp_gain_at?ago(p.last_xp_gain_at):'—'}</td><td class="xp">${fmt(p.xp)}</td><td class="daily">${fmt(daily[p.id]||0)}</td></tr>`}).join('');return `<section class="group"><div class="group-head"><span class="group-title">${esc(g.name)}</span><span class="group-count">${list.length} jogadores</span></div><div class="table-scroll"><table><thead><tr><th>JOGADOR</th><th>LEVEL</th><th>STATUS</th><th>XP/H</th><th>ÚLTIMO GANHO</th><th>EXP</th><th>XP HOJE</th></tr></thead><tbody>${body}</tbody></table></div></section>`}).join('');document.querySelector('#groups').innerHTML=html||'<div class="group empty">Nenhum jogador encontrado.</div>';
const tracked=new Set(players.map(p=>p.name.toLowerCase()));const deathList=deaths.filter(d=>tracked.has(String(d.player_name||'').toLowerCase())).sort((a,b)=>Date.parse(b.died_at)-Date.parse(a.died_at)).slice(0,100);const dbody=deathList.map(d=>`<tr><td>${d.died_at?new Date(d.died_at).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'}</td><td><b>${esc(d.player_name)}</b> <span class="death-level">lvl ${fmt(d.level)}</span></td><td>${esc(d.reason||'Morte registrada')}</td></tr>`).join('');document.querySelector('#deaths').innerHTML=`<section class="group death-group"><div class="group-head"><span class="group-title">☠ DEATH LIST</span><span class="group-count">${deathList.length} mortes</span></div><div class="table-scroll"><table class="death-table"><thead><tr><th>HORÁRIO</th><th>JOGADOR</th><th>MORREU PARA</th></tr></thead><tbody>${dbody||'<tr><td colspan="3" class="empty">Nenhuma morte registrada.</td></tr>'}</tbody></table></div></section>`;
document.querySelector('#up').textContent=up;document.querySelector('#stop').textContent=stop;document.querySelector('#off').textContent=off;document.querySelector('#playerTotal').textContent=players.length;document.querySelector('#dailyTotal').textContent=fmt(Object.values(daily).reduce((a,b)=>a+b,0));document.querySelector('#updated').textContent=new Date().toLocaleTimeString('pt-BR');document.querySelector('#sync').textContent='● AO VIVO · '+new Date().toLocaleTimeString('pt-BR');}
function localDayKey(iso){const d=new Date(iso);return d.toLocaleDateString('sv-SE',{timeZone:'America/Sao_Paulo'});}
async function load(){const [g,p,d,h]=await Promise.all([db.from('tracker_groups').select('id,name,slug,kind,active,sort_order').eq('active',true).order('sort_order'),db.from('players').select('id,name,level,status,xp,xp_per_hour,last_xp_gain_at,group,group_id').order('name'),db.from('player_deaths').select('player_id,player_name,level,reason,died_at').order('died_at',{ascending:false}).limit(100),db.from('player_xp_history').select('player_id,xp,recorded_at').order('recorded_at',{ascending:false}).limit(5000)]);if(g.error||p.error||d.error||h.error){document.querySelector('#groups').innerHTML='<div class="group empty">Erro ao carregar dados: '+esc((g.error||p.error||d.error||h.error).message)+'</div>';return}const today=new Date().toLocaleDateString('sv-SE',{timeZone:'America/Sao_Paulo'}),by={};(h.data||[]).filter(x=>localDayKey(x.recorded_at)===today).forEach(x=>{if(!by[x.player_id])by[x.player_id]=[];by[x.player_id].push(Number(x.xp)||0)});const daily={};Object.entries(by).forEach(([id,arr])=>{daily[id]=Math.max(0,Math.max(...arr)-Math.min(...arr))});state={...state,groups:g.data||[],players:p.data||[],deaths:d.data||[],daily};render();}
function clock(){document.querySelector('#clock').textContent=new Date().toLocaleTimeString('pt-BR');const now=Date.now(),next=Math.ceil(now/180000)*180000,sec=Math.max(0,Math.ceil((next-now)/1000)),m=String(Math.floor(sec/60)).padStart(2,'0'),s=String(sec%60).padStart(2,'0');const el=document.querySelector('#nextRefresh');if(el)el.textContent=`${m}:${s}`;}
let reloadTimer=null;function scheduleReload(){clearTimeout(reloadTimer);reloadTimer=setTimeout(load,250)}
load();const realtime=db.channel('elenor-viewer-live').on('postgres_changes',{event:'*',schema:'public',table:'players'},scheduleReload).on('postgres_changes',{event:'*',schema:'public',table:'tracker_groups'},scheduleReload).on('postgres_changes',{event:'*',schema:'public',table:'player_deaths'},scheduleReload).on('postgres_changes',{event:'*',schema:'public',table:'player_xp_history'},scheduleReload).subscribe();
setInterval(clock,1000);setInterval(load,180000);clock();
document.querySelector('#refresh')?.addEventListener('click',()=>{document.querySelector('#sync').textContent='● Atualizando...';load()});document.querySelector('#search')?.addEventListener('input',e=>{state.search=e.target.value;render()});document.querySelector('#statusFilter')?.addEventListener('change',e=>{state.filter=e.target.value;render()});
